services:
  glm-ocr:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: glm-ocr-service
    restart: unless-stopped
    ports:
      - "18030:8080"
    devices:
      - /dev/dxg:/dev/dxg
    volumes:
      - ./models/glm-ocr-ov:/models/glm-ocr:rw
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro
      - ./models/hf-cache:/models/hf-cache:rw
    environment:
      LD_LIBRARY_PATH: /usr/lib/wsl/lib
      HF_HOME: /models/hf-cache
    command: ["--device", "GPU", "--port", "8080"]
